development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: site_development
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: site_test
production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: miner_production
  pool: 5
  username: root
  password:
