#!/usr/bin/env ruby
require File.expand_path('../../config/environment',  __FILE__)

Mine.all(1).each do |gem|
  rock = Rock.find_or_initialize_by_name(gem.name)
  rock.update_attributes(:description => gem.info, :authors => gem.authors, :score => gem.score)
end
